name: Workflow for unit-testing

on:
  push:
    branches:
      - unit-testing

jobs:

  UnitTests:
    name: Unit Tests
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run Unit Tests
        env:
          SPRING_PROFILES_ACTIVE: test
        run: mvn test

  integration-tests:
    name: Integration Tests with MySQL
    runs-on: ubuntu-20.04
    needs: unit-tests

    services:
      db:
        image: mysql:8.3
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: world
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Wait for Database
        run: sleep 30

      - name: Run Integration Tests
        env:
          SPRING_PROFILES_ACTIVE: integration
        run: mvn test verify
