name: workflow for unit testing branch

on:
  push:
    branches:
      - unit-testing
jobs:

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run Unit Tests
        env:
          SPRING_PROFILES_ACTIVE: test
        run: mvn test
